export const ANSWERS = [
  {
    subject: "Planificación y administración de redes",
    title:
      "¿Cuál de las siguientes tecnologías implementa una mayor seguridad?",
    answer_1: "WPA3",
    answer_2: "WPA5",
    answer_3: "WPA2",
    answer_4: "WPA4",
    correct_answer: "WPA3",
  },
  {
    subject: "Planificación y administración de redes",
    title: "¿Cuál de los siguientes comandos usa mensajes de echo?",
    answer_1: "ping",
    answer_2: "tftp",
    answer_3: "arp",
    answer_4: "telnet",
    correct_answer: "ping",
  },
  {
    subject: "Planificación y administración de redes",
    title:
      "¿Cuál de los siguientes protocolos de enrutamiento se puede configurar en un router CISCO?",
    answer_1: "RIPv2",
    answer_2: "RIPv10",
    answer_3: "RIPv7",
    answer_4: "Todos se pueden configurar",
    correct_answer: "RIPv2",
  },
  {
    subject: "Planificación y administración de redes",
    title: "¿Cuál es generalmente la VLAN dedicada a la administración?",
    answer_1: "VLAN 99",
    answer_2: "VLAN 30",
    answer_3: "VLAN 45",
    answer_4: "VLAN 2",
    correct_answer: "VLAN 99",
  },
  {
    subject: "Planificación y administración de redes",
    title: "¿Cuál es la implementación que regula las VLAN?",
    answer_1: "IEEE 802.1q",
    answer_2: "IEEE 802.3q",
    answer_3: "IEEE 802.2q",
    answer_4: "IEEE 802.1e",
    correct_answer: "IEEE 802.1q",
  },
  {
    subject: "Planificación y administración de redes",
    title: "¿Cuántos bytes contiene una dirección IPv4?",
    answer_1: "4 bytes",
    answer_2: "Ninguna es correcta",
    answer_3: "32 bits",
    answer_4: "8 bytes",
    correct_answer: "4 bytes",
  },
  {
    subject: "Planificación y administración de redes",
    title: "¿Dónde deben de ubicarse las ACL extendidas?",
    answer_1: "Lo más cerca posible del origen del tráfico denegado",
    answer_2: "En cualquier sitio, es independiente",
    answer_3: "Lo más lejos posible del origen del tráfico denegado",
    answer_4: "Lo más cerca posible del origen del tráfico aceptado",
    correct_answer: "Lo más cerca posible del origen del tráfico denegado",
  },
  {
    subject: "Planificación y administración de redes",
    title: "¿En qué nivel del modelo OSI opera un switch?",
    answer_1: 3,
    answer_2: 2,
    answer_3: 1,
    answer_4: 4,
    correct_answer: "2",
  },
  {
    subject: "Planificación y administración de redes",
    title: "A la hora de diseñar una red, debemos de tener en cuenta:",
    answer_1: "Ninguna de las anteriores es correcta.",
    answer_2: "Que la instalación sea diseñada por un arquitecto",
    answer_3: "Que no haya cables cerca.",
    answer_4: "El sistema operativo de los equipos que se van a conectar.",
    correct_answer: "Ninguna de las anteriores es correcta.",
  },
  {
    subject: "Planificación y administración de redes",
    title: "Algunos de los problemas de transmisión son:",
    answer_1: "Ninguna de las anteriores es correcta.",
    answer_2: "La atenuación, las tramas y el ruido.",
    answer_3: "Las microondas, la distorsión y el ruido.",
    answer_4: "Las microondas, las tramas y el ruido.",
    correct_answer: "Ninguna de las anteriores es correcta.",
  },
  {
    subject: "Planificación y administración de redes",
    title:
      "Comprobación de Redundancia Vertical, ¿cuáles son sus siglas? Ten en cuenta que son las siglas en inglés.",
    answer_1: "RVC",
    answer_2: "Ninguna es correcta",
    answer_3: "CRV",
    answer_4: "VCR",
    correct_answer: "VCR",
  },
  {
    subject: "Planificación y administración de redes",
    title: "El actual sistema de defensa de la red Wifi es:",
    answer_1: "WPA3.",
    answer_2: "WPA4.",
    answer_3: "WPA2.",
    answer_4: "WPA3.A1.",
    correct_answer: "WPA3.",
  },
  {
    subject: "Planificación y administración de redes",
    title: "El protocolo OSPF, ¿es un protocolo interior o exterior?",
    answer_1: "Híbrido",
    answer_2: "Interior",
    answer_3: "Exterior",
    answer_4: "No es un protocolo",
    correct_answer: "Interior",
  },
  {
    subject: "Planificación y administración de redes",
    title: "El ruido de diafonía se genera cuando:",
    answer_1:
      "Dos cables están muy próximos y uno recibe las señales que transmite el otro.",
    answer_2:
      "Al apagar ciertos dispositivos o componentes se producen picos en la amplitud de duración muy reducida",
    answer_3:
      "Tenemos alguna fuente externa que produzca ondas electromagnéticas.",
    answer_4:
      "La agitación de los electrones en el propio cable produce un aumento de temperatura.",
    correct_answer:
      "Dos cables están muy próximos y uno recibe las señales que transmite el otro.",
  },
  {
    subject: "Planificación y administración de redes",
    title: "En el control mediante paso de testigo, el testigo, ¿qué es?",
    answer_1: "Una trama",
    answer_2: "Un switch",
    answer_3: "Un ordenador",
    answer_4: "Un router",
    correct_answer: "Una trama",
  },
  {
    subject: "Planificación y administración de redes",
    title:
      "En función de sus miembros es el tipo de VLAN que depende de su dirección IP de red:",
    answer_1: "Nivel 3.",
    answer_2: "Nivel 2.",
    answer_3: "Nivel 1.",
    answer_4: "Ninguna de las anteriores.",
    correct_answer: "Nivel 3.",
  },
  {
    subject: "Planificación y administración de redes",
    title: "Es un protocolo híbrido de enrutamiento:",
    answer_1: "OSPF",
    answer_2: "IGRP",
    answer_3: "IS-IS",
    answer_4: "Ninguno es un protocolo dinámico",
    correct_answer: "IS-IS",
  },
  {
    subject: "Planificación y administración de redes",
    title: "Indica cuál de las siguientes afirmaciones es cierta:",
    answer_1: "La tarjeta de red puede ser cableada o inalámbrica",
    answer_2: "El software de red solo se implementa en un equipo servidor",
    answer_3: "Una red no necesita de equipos terminales",
    answer_4: "El medio de una red siempre es el mismo, solo cableado",
    correct_answer: "La tarjeta de red puede ser cableada o inalámbrica",
  },
  {
    subject: "Planificación y administración de redes",
    title:
      "Indica cuál de las siguientes direcciones IPv4 se puede considerar una dirección pública.",
    answer_1: "172.32.0.1",
    answer_2: "172.24.58.27",
    answer_3: "10.0.0.24",
    answer_4: "192.168.1.5",
    correct_answer: "172.32.0.1",
  },
  {
    subject: "Planificación y administración de redes",
    title: "Indica cuál de las siguientes es una funcionalidad de un switch:",
    answer_1: "Todas son correctas",
    answer_2: "QoS",
    answer_3: "Administración remota",
    answer_4: "ACL",
    correct_answer: "Todas son correctas",
  },
  {
    subject: "Planificación y administración de redes",
    title: "Indica cuál de las siguientes es una topología de red básica:",
    answer_1: "Todas son topologías de red básicas",
    answer_2: "En estrella",
    answer_3: "En malla",
    answer_4: "En anillo",
    correct_answer: "Todas son topologías de red básicas",
  },
  {
    subject: "Planificación y administración de redes",
    title:
      "Indica en notación CIDR la dirección IP 10.1.0.0 con máscara 255.240.0.0:",
    answer_1: "10.1.0.0 - 12",
    answer_2: "10.1.0.0/12",
    answer_3: "255.240.0.0/10.1.0.0",
    answer_4: "12/10.1.0.0",
    correct_answer: "10.1.0.0/12",
  },
  {
    subject: "Planificación y administración de redes",
    title: "La atenuación implica que a lo largo del tiempo se pierda…",
    answer_1: "Amplitud",
    answer_2: "Fase",
    answer_3: "Periodo",
    answer_4: "Longitud",
    correct_answer: "Amplitud",
  },
  {
    subject: "Planificación y administración de redes",
    title: "La redundancia, ¿es interesante en las redes?",
    answer_1: "Sí",
    answer_2: "No",
    answer_3: "Depende de lo que la empresa necesite",
    answer_4: "Depende de si la VLAN es de administración o no",
    correct_answer: "Depende de lo que la empresa necesite",
  },
  {
    subject: "Planificación y administración de redes",
    title: "La seguridad de red de un switch se basa en:",
    answer_1: "Las dos anteriores son correctas.",
    answer_2: "La anulación de equipos no autorizados.",
    answer_3: "El reenvío selectivo.",
    answer_4: "Ninguna de las anteriores es correcta.",
    correct_answer: "Las dos anteriores son correctas.",
  },
  {
    subject: "Planificación y administración de redes",
    title: "La siguiente imagen, ¿qué es?:",
    answer_1: "Crimpadora de RJ45",
    answer_2: "Pelacables",
    answer_3: "Grimpadora de cable coaxial",
    answer_4: "Crimpadora de cable coaxial",
    correct_answer: "Crimpadora de cable coaxial",
  },
  {
    subject: "Planificación y administración de redes",
    title: "La tasa de baudios se encuentra en:",
    answer_1: "Las señales moduladas.",
    answer_2: "Las señales digitales.",
    answer_3: "Las señales analógicas.",
    answer_4: "Ninguna de las anteriores.",
    correct_answer: "Las señales moduladas.",
  },
  {
    subject: "Planificación y administración de redes",
    title: "La transmisión en paralelo destaca por:",
    answer_1: "Su alta velocidad, pero a un alto coste.",
    answer_2: "Su baja velocidad, pero bajo coste.",
    answer_3: "Su bajo coste y alta velocidad.",
    answer_4: "Su alto coste para una baja velocidad.",
    correct_answer: "Su alta velocidad, pero a un alto coste.",
  },
  {
    subject: "Planificación y administración de redes",
    title: "Las direcciones especiales 127.0.0.1 – 127.255.255.255 son:",
    answer_1: "Bucle local o Loopback.",
    answer_2: "Todas las anteriores son incorrectas.",
    answer_3: "Mi propio host.",
    answer_4: "Enlace local.",
    correct_answer: "Bucle local o Loopback.",
  },
  {
    subject: "Planificación y administración de redes",
    title: "Las técnicas de conmutación suelen darse en redes:",
    answer_1: "WAN",
    answer_2: "LAN",
    answer_3: "PAN",
    answer_4: "VLAN",
    correct_answer: "WAN",
  },
  {
    subject: "Planificación y administración de redes",
    title: "Los armarios o rack de comunicaciones suelen emplearse en:",
    answer_1: "Los CPD.",
    answer_2: "Empresas que dispongan de cuartos de entradas de servicios.",
    answer_3: "Grandes empresas.",
    answer_4: "Ninguno de los anteriores.",
    correct_answer: "Los CPD.",
  },
  {
    subject: "Planificación y administración de redes",
    title:
      "Los cortafuegos de los routers domésticos examinan los datos, ¿de qué cadenas?:",
    answer_1: "Todas las anteriores son correctas.",
    answer_2: "OUTPUT.",
    answer_3: "INPUT.",
    answer_4: "FORWARD.",
    correct_answer: "Todas las anteriores son correctas.",
  },
  {
    subject: "Planificación y administración de redes",
    title: "Los routers trabajan en este nivel del modelo OSI:",
    answer_1: "3.",
    answer_2: "5.",
    answer_3: "2.",
    answer_4: "4.",
    correct_answer: "3.",
  },
  {
    subject: "Planificación y administración de redes",
    title: "Los routers, ¿tienen sistema operativo?",
    answer_1: "Sí",
    answer_2: "Depende del modelo",
    answer_3: "No",
    answer_4: "Depende del tipo de router",
    correct_answer: "Sí",
  },
  {
    subject: "Planificación y administración de redes",
    title: "No es un tipo de conmutación en redes:",
    answer_1: "De redes.",
    answer_2: "De paquetes.",
    answer_3: "De circuitos.",
    answer_4: "Todas las anteriores son incorrectas.",
    correct_answer: "De redes.",
  },
  {
    subject: "Planificación y administración de redes",
    title:
      "Protocolo encargado de asociar un nombre en concreto con una dirección IP con la intención de poder localizar un host sin necesidad de escribir su dirección IP completa:",
    answer_1: "DNS.",
    answer_2: "Ninguna de las anteriores es correcta.",
    answer_3: "FTP.",
    answer_4: "SMTP.",
    correct_answer: "DNS.",
  },
  {
    subject: "Planificación y administración de redes",
    title:
      "Sabiendo que el ancho de banda de referencia es 108 y que Ethernet tiene un ancho de banda de de 107, ¿Cuál será su coste de interfaz?:",
    answer_1: 10,
    answer_2: 100,
    answer_3: 1,
    answer_4: 0,
    correct_answer: "10",
  },
  {
    subject: "Planificación y administración de redes",
    title:
      "Si los datagramas que se envían no tuvieran un campo que indica su TTL, tiempo de vida, estos:",
    answer_1:
      "Podría permanecer dando vueltas de manera indefinida por la red.",
    answer_2: "Se eliminaría en el momento de ser enviado.",
    answer_3:
      "Se eliminaría en el momento en el que no encontrará su objetivo, sin volver a intentarlo.",
    answer_4: "Todas las anteriores son incorrectas.",
    correct_answer:
      "Podría permanecer dando vueltas de manera indefinida por la red.",
  },
  {
    subject: "Planificación y administración de redes",
    title:
      "Ventaja del diseño de red jerárquico producida por su diseño modular:",
    answer_1: "Escalabilidad.",
    answer_2: "Rendimiento.",
    answer_3: "Seguridad.",
    answer_4: "Facilidad administrativa.",
    correct_answer: "Escalabilidad.",
  },
  {
    subject: "Planificación y administración de redes",
    title: "WireShark:",
    answer_1: "Todas son correctas.",
    answer_2: "Permite realizar capturas del tráfico de red.",
    answer_3: "Es una aplicación de terceros.",
    answer_4: "Se puede instalar tanto en Windows como en Linux",
    correct_answer: "Todas son correctas.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "¿Cuál de las siguientes es una tendencia actual relativa a la comunicación interna?:",
    answer_1: "Motor de digitalización.",
    answer_2: "Employer Branding.",
    answer_3: "Apps internas.",
    answer_4: "Todas son correctas.",
    correct_answer: "Todas son correctas.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "¿Cuál de las siguientes no es una de las 5 fuerzas de Porter?:",
    answer_1: "El poder de negociación de los proveedores.",
    answer_2: "La amenaza de productos sustitutivos.",
    answer_3: "El flujo del proceso de compraventa.",
    answer_4: "Las barreras de entrada.",
    correct_answer: "El flujo del proceso de compraventa.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "¿Cuál de las siguientes no sería una estrategia del plan de marketing en función del producto?:",
    answer_1: "Estrategia de penetración.",
    answer_2: "Estrategia de desarrollo de producto.",
    answer_3: "Estrategia de enraizamiento.",
    answer_4: "Estrategia de diversificación.",
    correct_answer: "Estrategia de enraizamiento.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "¿Cuál es el objetivo principal del marketing relacional?:",
    answer_1: "Incrementar las ventas a corto plazo.",
    answer_2: "Atraer nuevos clientes a través de la publicidad masiva.",
    answer_3: "Realizar promociones y descuentos.",
    answer_4:
      "Mantener una relación significativa a largo plazo con el público objetivo.",
    correct_answer:
      "Mantener una relación significativa a largo plazo con el público objetivo.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "¿Cuál es la definición más completa de marketing?:",
    answer_1: "El proceso de ventas de bienes y servicios.",
    answer_2:
      "El estudio de la competencia y el comportamiento del consumidor.",
    answer_3: "La actividad de publicidad y análisis de mercado.",
    answer_4:
      "La planificación y ejecución de la concepción del producto, fijación de precios, promoción y distribución de ideas, bienes y servicios para crear relaciones de intercambio que satisfagan objetivos individuales y organizacionales.",
    correct_answer:
      "La planificación y ejecución de la concepción del producto, fijación de precios, promoción y distribución de ideas, bienes y servicios para crear relaciones de intercambio que satisfagan objetivos individuales y organizacionales.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "¿Cuál es la principal diferencia entre marketing estratégico y marketing operativo?:",
    answer_1:
      "El marketing estratégico se centra en el corto plazo, mientras que el operativo se centra en el largo plazo.",
    answer_2:
      "El marketing estratégico se ocupa de la implementación de acciones, mientras que el operativo se ocupa del análisis de necesidades del público objetivo.",
    answer_3:
      "El marketing estratégico se ocupa de la publicidad, mientras que el marketing operativo se centra en las ventas.",
    answer_4:
      "El marketing estratégico se centra en el análisis continuo y la identificación de necesidades del público objetivo, mientras que el marketing operativo se focaliza en la puesta en marcha de medidas para aprovechar oportunidades.",
    correct_answer:
      "El marketing estratégico se centra en el análisis continuo y la identificación de necesidades del público objetivo, mientras que el marketing operativo se focaliza en la puesta en marcha de medidas para aprovechar oportunidades.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "¿Cuál es la principal herramienta del marketing estratégico?:",
    answer_1: "Análisis DAFO.",
    answer_2: "Estrategia de precios.",
    answer_3: "Investigación de mercado.",
    answer_4: "Plan de marketing.",
    correct_answer: "Plan de marketing.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "¿En qué se basa la decisión que se toma para cubrir necesidades?:",
    answer_1: "En un impulso.",
    answer_2: "En una imitación de lo que hace la sociedad.",
    answer_3: "En una encuesta.",
    answer_4: "En una comparativa.",
    correct_answer: "En una comparativa.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "¿Qué análisis no forma parte del análisis de la situación en el plan de marketing?:",
    answer_1: "Análisis de la demanda.",
    answer_2: "Análisis de la competencia.",
    answer_3: "Análisis del producto.",
    answer_4: "Análisis interno de la empresa.",
    correct_answer: "Análisis del producto.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "¿Qué herramienta permite analizar las debilidades, amenazas, fortalezas y oportunidades de una empresa??:",
    answer_1: "Análisis PEST.",
    answer_2: "Matriz de crecimiento.",
    answer_3: "Investigación de mercado.",
    answer_4: "Análisis DAFO.",
    correct_answer: "Análisis DAFO.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "A las personas que, sin haber sido dotadas de autoridad, tienen la capacidad de influenciar sobre los demás por su carisma y personalidad, se les denomina:",
    answer_1: "Jefes.",
    answer_2: "Directores.",
    answer_3: "Líderes.",
    answer_4: "Mandos.",
    correct_answer: "Líderes.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "Al responsable de recursos humanos se le presuponen varias habilidades, entre ellas:",
    answer_1: "Tener motivación y ser capaz de trasmitirla al equipo.",
    answer_2: "Comunicar efectivamente.",
    answer_3: "Ser resolutivo y determinado en la toma de decisiones.",
    answer_4: "Todas son correctas.",
    correct_answer: "Todas son correctas.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "Cuando hablamos de segmentación, la estrategia de expansión de mercado:",
    answer_1: "Ofrecerá distintos productos a un solo segmento.",
    answer_2: "Actuará en un solo segmento con un solo producto.",
    answer_3: "Se centrará en más de un segmento, pero con un solo producto.",
    answer_4: "Adaptará el producto a las particularidades de cada segmento.",
    correct_answer:
      "Se centrará en más de un segmento, pero con un solo producto.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "Dentro de las teorías del liderazgo, la teoría del gran hombre afirma que:",
    answer_1: "de sus subordinados,",
    answer_2:
      "El comportamiento del líder depende de la percepción que tenga de la naturaleza",
    answer_3:
      "Los rasgos del líder son innatos y no se pueden adquirir ni con entrenamiento ni con experiencia.",
    answer_4:
      "Solo puede existir un líder en la organización, que ejercerá su mando con mano de hierro.",
    correct_answer:
      "Los rasgos del líder son innatos y no se pueden adquirir ni con entrenamiento ni con experiencia.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "Documento formal que incorpora una orden de pago, por la que una persona ordena pagar una determinada cantidad de dinero al poseedor de esta a su vencimiento:",
    answer_1: "Cheque.",
    answer_2: "Transferencia bancaria.",
    answer_3: "Recibo normalizado.",
    answer_4: "Letra de cambio.",
    correct_answer: "Letra de cambio.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "El Estado puede conseguir los ingresos públicos de:",
    answer_1: "Las donaciones y la deuda pública.",
    answer_2: "La extracción o expropiación.",
    answer_3: "Los ingresos contractuales.",
    answer_4: "Todas son correctas.",
    correct_answer: "Todas son correctas.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "El estilo de liderazgo en el que el líder interviene solo cuando lo cree conveniente, dejando máxima libertad a sus empleados y controlando lo mínimo imprescindible, se denomina:",
    answer_1: "Liderazgo paternalista.",
    answer_2: "Liderazgo democrático.",
    answer_3: "Liderazgo laissez faire.",
    answer_4: "Liderazgo visionario.",
    correct_answer: "Liderazgo laissez faire.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "El estilo de liderazgo en el que el líder tiene claro dónde quiere ir e intenta que el equipo visualice su meta y la comparta, se denomina:",
    answer_1: "Liderazgo laissez faire.",
    answer_2: "Liderazgo democrático.",
    answer_3: "Liderazgo paternalista.",
    answer_4: "Liderazgo visionario.",
    correct_answer: "Liderazgo visionario.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "El factor que impulsa a las personas a iniciar, mantener o terminar una actividad, un comportamiento o una actitud se denomina:",
    answer_1: "Autoestima.",
    answer_2: "Pirámide de necesidades.",
    answer_3: "Motivación.",
    answer_4: "Higiénico.",
    correct_answer: "Motivación.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "El impuesto que se encarga de gravar el consumo es:",
    answer_1: "El Impuesto sobre Sociedades.",
    answer_2: "El IRPF.",
    answer_3: "El IVA.",
    answer_4: "La declaración censal.",
    correct_answer: "El IVA.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "El Impuesto sobre Sociedades:",
    answer_1: "Tiene carácter indirecto.",
    answer_2:
      "Grava la ganancia de rentas por parte de personas físicas y entidades públicas.",
    answer_3:
      "Es de naturaleza personal porque tiene en cuenta determinadas circunstancias particulares de cada contribuyente.",
    answer_4: "Ninguna es correcta.",
    correct_answer:
      "Es de naturaleza personal porque tiene en cuenta determinadas circunstancias particulares de cada contribuyente.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "El presupuesto familiar se compone de:",
    answer_1: "Gastos fijos.",
    answer_2: "Gastos corrientes.",
    answer_3: "Gastos ocasionales.",
    answer_4: "Todas son correctas.",
    correct_answer: "Todas son correctas.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "Engloba todas las tareas dirigidas a la obtención y transformación de los recursos que permiten desarrollar la actividad de la empresa y aprovechar las oportunidades de mercado, delimitando el plan de actuación que llevará a la generación de beneficios económicos:",
    answer_1: "Aprovisionamiento.",
    answer_2: "Sistema de mercado.",
    answer_3: "Ciclo de explotación.",
    answer_4: "Marketing relacional.",
    correct_answer: "Ciclo de explotación.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "Entre los objetivos del análisis de los puestos de trabajo se encuentra:",
    answer_1: "Ayudar al reclutamiento y selección de personal.",
    answer_2: "Detectar necesidades de formación.",
    answer_3: "Prever los costes salariales.",
    answer_4: "Todas son correctas.",
    correct_answer: "Todas son correctas.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "Es una modificación de la jerarquía de Maslow que clasifica las necesidades básicas en tres subgrupos (existencia, relación y crecimiento):",
    answer_1: "Teoría de McGregor.",
    answer_2: "Pirámide de las tres esquinas.",
    answer_3: "Teoría ERG.",
    answer_4: "Jerarquía de Adams.",
    correct_answer: "Teoría ERG.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "La Agencia Tributaria:",
    answer_1:
      "Es una entidad de derecho público adscrita al Ministerio de Hacienda.",
    answer_2:
      "Se misión es aplicar el sistema tributario y hacer cumplir el artículo 31 de la Constitución.",
    answer_3: "Se creó en 1992.",
    answer_4: "Todas son correctas.",
    correct_answer: "Todas son correctas.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "La demanda dependerá, entre otros, de:",
    answer_1: "El comportamiento del consumidor.",
    answer_2: "El precio del producto.",
    answer_3: "La renta disponible y su distribución.",
    answer_4: "Todas son correctas.",
    correct_answer: "Todas son correctas.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "La organización formal:",
    answer_1:
      "Es aquella que procura que su estructura esté en todo momento provista de personal, en sentido tanto cuantitativo como cualitativo.",
    answer_2:
      "Es aquella donde la estructura organizativa está conformada según las relaciones personales que surgen de forma natural entre los trabajadores.",
    answer_3:
      "Es aquella donde la estructura organizativa la definen los directivos y se refleja en un organigrama con los puestos de trabajo, relaciones jerárquicas y funciones.",
    answer_4:
      "Es aquella que impulsa la transformación digital implicando a todos los integrantes en el uso de la tecnología para fomentar un ecosistema abierto y digitalizado.",
    correct_answer:
      "Es aquella donde la estructura organizativa la definen los directivos y se refleja en un organigrama con los puestos de trabajo, relaciones jerárquicas y funciones.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "La organización informal:",
    answer_1:
      "Es aquella donde la estructura organizativa la define la dirección y se refleja en un organigrama con los puestos de trabajo, relaciones jerárquicas y funciones.",
    answer_2:
      "Es aquella que impulsa la transformación digital implicando a todos los integrantes en el uso de la tecnología para fomentar un ecosistema abierto y digitalizado.",
    answer_3:
      "Es aquella que procura que su estructura esté en todo momento provista de personal, en sentido tanto cuantitativo como cualitativo.",
    answer_4:
      "Es aquella donde la estructura organizativa está conformada según las relaciones personales que surgen de forma natural entre los trabajadores.",
    correct_answer:
      "Es aquella donde la estructura organizativa está conformada según las relaciones personales que surgen de forma natural entre los trabajadores.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "La planificación para establecer el personal de una organización se realiza en dos direcciones:",
    answer_1: "Expansión laboral y fusión de centros.",
    answer_2:
      "Ninguna empresa realiza ya planificaciones de los recursos humanos.",
    answer_3: "Renovación de puestos y reciclaje de puestos actuales.",
    answer_4: "Aumento de personal y reducción de personal.",
    correct_answer: "Aumento de personal y reducción de personal.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "La T.A.E. (Tasa Anual Equivalente) es la suma de:",
    answer_1:
      "Comisión de apertura, comisión de estudio y comisión por cancelación.",
    answer_2: "Préstamos, créditos y sus correspondientes tipos de interés.",
    answer_3: "Amortización fija, amortización permanente e impuestos.",
    answer_4: "Interés nominal, comisiones y gastos.",
    correct_answer: "Interés nominal, comisiones y gastos.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "Las normas internas que son establecidas por la dirección para determinar objetivos y prácticas de comunicación comunes para toda la empresa son lo que se denomina:",
    answer_1: "Planificación de RRHH.",
    answer_2: "Flujo comunicativo.",
    answer_3: "Comunicación vertical.",
    answer_4: "Política de comunicación.",
    correct_answer: "Política de comunicación.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "Las prestaciones pecuniarias exigidas por una Administración pública, como consecuencia de la realización del supuesto de hecho al que la ley vincula el deber de contribuir, se denominan:",
    answer_1: "Tesorerías.",
    answer_2: "Recibos.",
    answer_3: "Tributos.",
    answer_4: "Letras de cambio.",
    correct_answer: "Tributos.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "Los grupos profesionales se definen por:",
    answer_1: "Las características del trabajador.",
    answer_2: "La titulación del trabajador.",
    answer_3: "Las aptitudes del trabajador.",
    answer_4: "Todas son correctas.",
    correct_answer: "Todas son correctas.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "Los indicadores más habituales en el balance social son:",
    answer_1: "Las variables, los tipos y las consecuencias.",
    answer_2: "Locales, regionales, nacionales e internacionales.",
    answer_3: "Inputs, outputs e insiders.",
    answer_4: "La eficiencia, la eficacia y el impacto.",
    correct_answer: "La eficiencia, la eficacia y el impacto.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "Los préstamos personales:",
    answer_1: "Suelen tener un plazo máximo de amortización de hasta 15 años.",
    answer_2:
      "Sus intereses siempre son inferiores a los de los créditos hipotecarios.",
    answer_3: "Se conocen normalmente como préstamos al consumo.",
    answer_4: "Todas son correctas.",
    correct_answer: "Se conocen normalmente como préstamos al consumo.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "Los recursos humanos se conciben desde tres enfoques:",
    answer_1: "Político-legal, socioeconómico y laboral.",
    answer_2: "Actitudinal, competencial y aptitudinal.",
    answer_3: "Administrativo-legal, contable-costes y de gestión.",
    answer_4: "Personal, empresarial y social.",
    correct_answer: "Administrativo-legal, contable-costes y de gestión.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title: "Para la planificación de los recursos humanos:",
    answer_1: "Es necesario plantear constantes aumentos de personal.",
    answer_2: "Todas son correctas.",
    answer_3: "Las desviaciones tienen siempre motivos extraordinarios.",
    answer_4: "Se marcan objetivos logísticos y estratégicos.",
    correct_answer: "Se marcan objetivos logísticos y estratégicos.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "Para poder elaborar un presupuesto familiar lo más fiel posible a la realidad, el primer paso es:",
    answer_1: "Establecer el ahorro con un ingreso fijo.",
    answer_2: "Contactar con un asesor fiscal.",
    answer_3: "Identificar gastos e ingresos.",
    answer_4: "Descargar el programa Excel.",
    correct_answer: "Identificar gastos e ingresos.",
  },
  {
    subject: "Ampliación de itinerario personal para la empleabilidad",
    title:
      "Renunciar a consumir hoy para consumir más en el futuro, ¿a qué concepto hace referencia?:",
    answer_1: "Consumo.",
    answer_2: "Financiación.",
    answer_3: "Planificación.",
    answer_4: "Ahorro.",
    correct_answer: "Ahorro.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "¿Cuáles son los controles de acceso más comunes?",
    answer_1: "Código de acceso.",
    answer_2: "Bandas magnéticas.",
    answer_3: "Biométrico.",
    answer_4: "Todas las anteriores son correctas.",
    correct_answer: "Todas las anteriores son correctas.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "¿Cuáles son los principales problemas que puede sufrir una señal?",
    answer_1: "Interrupción o corte de energía",
    answer_2: "Bajo voltaje momentáneo",
    answer_3: "Sobrevoltaje permanente.",
    answer_4: "Todas las anteriores son correctas.",
    correct_answer: "Todas las anteriores son correctas.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "¿Qué tipos de copia de seguridad existen?",
    answer_1: "Completa – Incrementales y Parciales",
    answer_2: "Incompleta – Incrementales y Diferenciales",
    answer_3: "Completa – Totales y Parciales",
    answer_4: "Completa – Incrementales y Diferenciales",
    correct_answer: "Completa – Incrementales y Diferenciales",
  },
  {
    subject: "Fundamentos de hardware",
    title:
      "A la hora del montaje de un equipo informático se debe tener en cuenta:",
    answer_1:
      "Apilar los componentes en una parte de la mesa para facilitar su uso.",
    answer_2: "Manipular la fuente de alimentación.",
    answer_3:
      "Si un componente no encaja bien, se debe forzar para su correcta instalación.",
    answer_4:
      "Evitar el polvo y la suciedad, al igual que descargarse de energía estática.",
    correct_answer:
      "Evitar el polvo y la suciedad, al igual que descargarse de energía estática.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "Algunas de las ventajas de la memoria DDR4 son:",
    answer_1: "Cuenta con una capacidad más elevada y están optimizadas.",
    answer_2: "Se aumenta hasta en un 50% el ancho de banda y el rendimiento.",
    answer_3: "Se aumenta el número de pines a 288.",
    answer_4: "Todas son correctas.",
    correct_answer: "Todas son correctas.",
  },
  {
    subject: "Fundamentos de hardware",
    title:
      "Algunos de los parámetros de un microprocesador hacen referencia a:",
    answer_1: "Memoria caché y tecnología de fabricación.",
    answer_2: "Velocidad del microprocesador y velocidad del bus.",
    answer_3: "VCore o voltaje del núcleo y núcleos de un microprocesador.",
    answer_4: "Todas son correctas.",
    correct_answer: "Todas son correctas.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "Cuando hablamos de RAID 1, nos referimos a:",
    answer_1:
      "Un tipo de raid que almacena la información dividida en dos bloques que se reparten entre los discos.",
    answer_2:
      "Un tipo de raid que realiza una copia incremental entre sus discos.",
    answer_3:
      "Un tipo de raid que realiza una copia en espejo, teniendo la información replicada en ambos discos.",
    answer_4: "Ninguna de las anteriores es correcta.",
    correct_answer:
      "Un tipo de raid que realiza una copia en espejo, teniendo la información replicada en ambos discos.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "El bajo voltaje permanente puede causar problemas cuando:",
    answer_1: "Cae más del 90% durante más de 60 segundos.",
    answer_2: "Cae más del 60% durante más de 30 segundos.",
    answer_3: "Cae más del 70% durante más de 40 segundos.",
    answer_4: "Cae más del 80% durante más de 50 segundos.",
    correct_answer: "Cae más del 90% durante más de 60 segundos.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "El chasis de un equipo microinformático:",
    answer_1:
      "Existen cuatro formatos de caja habitual: Formato estándar/Formato más pequeña/Formato grande E-ATX y Formato Mucro-ATX",
    answer_2:
      "El material destinado a la fabricación de chasis está compuesto únicamente por chapa troquelada.",
    answer_3:
      "Existen tres formatos de caja habitual: Formato estándar/Formato más pequeña y Formato grande E-ATX.",
    answer_4: "Todas las anteriores son correctas.",
    correct_answer:
      "Existen tres formatos de caja habitual: Formato estándar/Formato más pequeña y Formato grande E-ATX.",
  },
  {
    subject: "Fundamentos de hardware",
    title:
      "El componente de un circuito integrado que realiza operaciones aritméticas y lógicas es:",
    answer_1: "BIOS.",
    answer_2: "SoC.",
    answer_3: "ALU.",
    answer_4: "DDR4.",
    correct_answer: "ALU.",
  },
  {
    subject: "Fundamentos de hardware",
    title:
      "El concepto del aumento de la velocidad del microprocesador por encima de la que, en teoría, tiene es:",
    answer_1: "Hyperthreading.",
    answer_2: "PING.",
    answer_3: "Clúster.",
    answer_4: "Overlocking.",
    correct_answer: "Overlocking.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "El conector de sonido:",
    answer_1: "Rosa: Entrada de línea",
    answer_2: "Azul: Entrada de línea para micrófono",
    answer_3: "Verde: Salida de línea para altavoces",
    answer_4: "Todas son correctas.",
    correct_answer: "Verde: Salida de línea para altavoces",
  },
  {
    subject: "Fundamentos de hardware",
    title: "El conector USB tiene las características:",
    answer_1:
      "Características Plug and Play, pues tiene la opción de conectarlo y que no se pueda usar directamente.",
    answer_2: "Todas son correctas.",
    answer_3:
      "La velocidad del USB ha llegado a superar los 10000 Mbps en su versión 3.0",
    answer_4:
      "Puede usarse en conectores de USB 2.0/3.0, es decir tienen retrocompatibilidad.",
    correct_answer:
      "Puede usarse en conectores de USB 2.0/3.0, es decir tienen retrocompatibilidad.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "El particionamiento MBR da lugar a la partición:",
    answer_1: "Partición primaria.",
    answer_2: "Partición extendida.",
    answer_3: "Partición lógica.",
    answer_4: "Todas las anteriores son correctas.",
    correct_answer: "Todas las anteriores son correctas.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "El proceso de instalación de un procesador sería:",
    answer_1: "Liberar zócalo 2) Colocar el disipador 3) Añadir ventilador",
    answer_2: "Fijar el procesador en el zócalo 2) Colocar el disipador",
    answer_3:
      "Liberar zócalo 2) Colocar el procesador 3) Fijar el procesador en el zócalo 4) Añadir pasta térmica 5) Colocar el disipador",
    answer_4: "Todas las anteriores son incorrectas",
    correct_answer:
      "Liberar zócalo 2) Colocar el procesador 3) Fijar el procesador en el zócalo 4) Añadir pasta térmica 5) Colocar el disipador",
  },
  {
    subject: "Fundamentos de hardware",
    title: "El puerto HDMI es:",
    answer_1: "Conector interno.",
    answer_2: "Conector USB.",
    answer_3: "Conector externo.",
    answer_4: "Conector del Front Panel.",
    correct_answer: "Conector externo.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "El puerto PCI Express:",
    answer_1:
      "Utilizado únicamente por discos duros, debido a que se aprovecha su gran velocidad de procesamiento.",
    answer_2: "Todas las anteriores son incorrectas.",
    answer_3:
      "El puerto PCI Express sólo se utiliza para las tarjetas gráficas.",
    answer_4:
      "El puerto PCI Express puede tener varios pines o enlaces, desde 1 hasta 16.",
    correct_answer:
      "El puerto PCI Express puede tener varios pines o enlaces, desde 1 hasta 16.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "El servidor SAN emplea un cableado:",
    answer_1: "Trenzado.",
    answer_2: "Coaxial.",
    answer_3: "De fibra óptica.",
    answer_4: "Ninguna de las anteriores.",
    correct_answer: "De fibra óptica.",
  },
  {
    subject: "Fundamentos de hardware",
    title:
      "El socket que está compuesto por una matriz de conectores que conecta con los pines del microprocesador es:",
    answer_1: "Socket ML.",
    answer_2: "Socket PGA.",
    answer_3: "Socket LGA.",
    answer_4: "Socket DL.",
    correct_answer: "Socket PGA.",
  },
  {
    subject: "Fundamentos de hardware",
    title:
      "El tipo de tarjeta de expansión que se puede utilizar con conexión Ethernet es:",
    answer_1: "Tarjeta RAID.",
    answer_2: "Tarjeta gráfica.",
    answer_3: "Tarjeta de red.",
    answer_4: "Tarjeta capturadora.",
    correct_answer: "Tarjeta de red.",
  },
  {
    subject: "Fundamentos de hardware",
    title:
      "En las memorias solidas encontramos las siguientes características:",
    answer_1: "Cuentan con partes mecánicas.",
    answer_2: "Producen calor al trabajar sobre ellas.",
    answer_3: "Tienen un menor peso y son resistentes a los golpes.",
    answer_4: "El tiempo de búsqueda y de acceso es más lento.",
    correct_answer: "Tienen un menor peso y son resistentes a los golpes.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "Entre los parámetros de un microprocesador nos encontramos con:",
    answer_1: "Nos encontramos únicamente el overclocking.",
    answer_2:
      "Tecnólogia de fabricación: Es la responsable de los parámetros de un microprocesador.",
    answer_3:
      "Velocidad del microprocesador/ Velocidad del bus/Memoria caché/Tecnología de fabricación, vcore, nombre clave del núcleo, núcleos en un microprocesador, Hyperthreadin y Overclocking.",
    answer_4: "Todas son incorrectas.",
    correct_answer:
      "Velocidad del microprocesador/ Velocidad del bus/Memoria caché/Tecnología de fabricación, vcore, nombre clave del núcleo, núcleos en un microprocesador, Hyperthreadin y Overclocking.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "Formateo raro y que en condiciones normales no debe realizarse:",
    answer_1: "Formateo a alto nivel.",
    answer_2: "Formateo a medio nivel.",
    answer_3: "Formateo lógico.",
    answer_4: "Formateo a bajo nivel.",
    correct_answer: "Formateo a bajo nivel.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "La disponibilidad se calcula con la fórmula:",
    answer_1: "Disponibilidad = Uptime-(Uptime - Downtime).",
    answer_2: "Disponibilidad = Uptime+(Uptime / Downtime).",
    answer_3: "Disponibilidad = Uptime/(Uptime + Downtime)",
    answer_4: "Todas las anteriores son incorrectas.",
    correct_answer: "Disponibilidad = Uptime/(Uptime + Downtime)",
  },
  {
    subject: "Fundamentos de hardware",
    title: "La fiabilidad:",
    answer_1:
      "Se trata de una probabilidad del sistema de que durante un tiempo esté siempre accesible y en funcionamiento.",
    answer_2:
      "Se trata de un proceso para comprobar la fiabilidad del software de un sistema.",
    answer_3:
      "Se trata solamente de un proceso para comprobar el estado del hardware del sistema.",
    answer_4:
      "Se trata de una probabilidad que nos indica si pueden haber o no fallos en el sistema durante un tiempo.",
    correct_answer:
      "Se trata de una probabilidad que nos indica si pueden haber o no fallos en el sistema durante un tiempo.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "La memoria caché se puede encontrar en:",
    answer_1:
      "Su versión .L1, la cual tiene una mayor capacidad y menor velocidad.",
    answer_2:
      "Su versión L3, la cual funciona a máxima velocidad y se integra en el procesador.",
    answer_3:
      "Su versión L2, la cual se encuentra conectada al procesador en su bus delantero.",
    answer_4: "Ninguna de las anteriores es correcta.",
    correct_answer: "Ninguna de las anteriores es correcta.",
  },
  {
    subject: "Fundamentos de hardware",
    title:
      "¿Cuál de las siguientes afirmaciones describe correctamente la operación de escritura en la memoria?:",
    answer_1:
      "Se carga la dirección en el registro de datos y se copia el contenido de la celda en el registro de direcciones.",
    answer_2:
      "Se carga la dirección en el registro de direcciones, se carga el valor en el registro de datos, se localiza la celda mediante la decodificación y se volca el contenido del registro de datos en la celda de memoria.",
    answer_3:
      "Se decodifica la dirección y se copia el contenido de la celda en el registro de datos sin cargar la dirección.",
    answer_4:
      "Se localiza la celda mediante la decodificación sin cargar la dirección en el registro de direcciones y se copia el contenido de la celda en el registro de datos.",
    correct_answer:
      "Se carga la dirección en el registro de direcciones, se carga el valor en el registro de datos, se localiza la celda mediante la decodificación y se volca el contenido del registro de datos en la celda de memoria.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "La temperatura óptima en un CPD es de:",
    answer_1: "10 ºC.",
    answer_2: "12 ºC.",
    answer_3: "16 ºC.",
    answer_4: "Todas las anteriores son correctas.",
    correct_answer: "16 ºC.",
  },
  {
    subject: "Fundamentos de hardware",
    title:
      "Las hojas de cálculo, visores de fotos, visores de documentos, etc. son aplicaciones:",
    answer_1: "De IDE.",
    answer_2: "Del sistema.",
    answer_3: "De propósito general.",
    answer_4: "Todas las anteriores son incorrectas.",
    correct_answer: "De propósito general.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "Las ventajas de UEFI sobre Legacy BIOS son:",
    answer_1:
      "La energía y los recursos se gestionan de una manera más inestable.",
    answer_2: "Es menos fiable que Legacy BIOS.",
    answer_3: "Particiones con posibilidad de más de 2TB",
    answer_4: "Produce una carga menor al procesador.",
    correct_answer: "Particiones con posibilidad de más de 2TB",
  },
  {
    subject: "Fundamentos de hardware",
    title: "Los CDs y los DVDs son:",
    answer_1: "Memorias flash.",
    answer_2: "Dispositivos magnéticos.",
    answer_3: "Dispositivos ópticos.",
    answer_4: "Ninguna es correcta.",
    correct_answer: "Dispositivos ópticos.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "Los formatos más habituales de cajas o chasis de un equipo son:",
    answer_1: "Estándar.",
    answer_2: "Más pequeño.",
    answer_3: "Extended ATX.",
    answer_4: "Todas son correctas.",
    correct_answer: "Todas son correctas.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "Los plugins se consideran:",
    answer_1: "Malware.",
    answer_2: "Cookies.",
    answer_3: "Aplicaciones.",
    answer_4: "Todas las anteriores son incorrectas.",
    correct_answer: "Aplicaciones.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "Los principales requisitos que debe contar un CPD:",
    answer_1: "Suministro de ciberseguridad.",
    answer_2: "Temperatura y ambiente.",
    answer_3: "Seguridad física del local.",
    answer_4: "Debe estar construido en un sitio propenso a accidentes.",
    correct_answer: "Seguridad física del local.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "Los procesadores SOC",
    answer_1:
      "Son la base de los microprocesadores en lo referente a dispositivos móviles.",
    answer_2:
      "Tienen un consumo bastante menor en comparación a un procesador de x64",
    answer_3:
      "La diferencia entre un procesador SOC y una arquitectura estándar x86, es que esta última está basado en cuanto a potencia de cálculo y una velocidad alta",
    answer_4: "Todas las anteriores son correctas.",
    correct_answer: "Todas las anteriores son correctas.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "Los sistemas de archivos más utilizados son:",
    answer_1: "En dispositivos Linux: EXT",
    answer_2: "En dispositivos con Microsoft Windows: MBR",
    answer_3: "En los dispositivos Apple: HFS",
    answer_4: "Para memorias de almacenamiento tipo tarjeta SD: UEFI",
    correct_answer: "En dispositivos Linux: EXT",
  },
  {
    subject: "Fundamentos de hardware",
    title:
      "Se usa para cifrar todo el sistema y quitarles el acceso a los usuarios ya que no poseen la correspondiente clave:",
    answer_1: "Backdoors.",
    answer_2: "Exploit.",
    answer_3: "Adware.",
    answer_4: "Ransomware.",
    correct_answer: "Ransomware.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "Un RAID 5 compuesto por Disco 1, Disco 2 y Disco 3, siempre:",
    answer_1: "Guarda su copia de paridad en el disco 1",
    answer_2:
      "La copia de paridad irá alternándose entre el Disco 1 y Disco 2 dejando el Disco 3 para guardar la información.",
    answer_3: "La copia de paridad irá alternándose entre los 3 discos.",
    answer_4: "El disco 3 se utiliza únicamente para realizar backups.",
    correct_answer: "La copia de paridad irá alternándose entre los 3 discos.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "Un sistema informático está formado por:",
    answer_1: "Periféricos de entrada.",
    answer_2: "CPU.",
    answer_3: "Periféricos de salida.",
    answer_4: "Todas son correctas.",
    correct_answer: "Todas son correctas.",
  },
  {
    subject: "Fundamentos de hardware",
    title: "Una imagen grabada de un sistema operativo poseerá una extensión:",
    answer_1: ".xml.",
    answer_2: ".gtd.",
    answer_3: ".iso.",
    answer_4: "Ninguna de las anteriores es correcta.",
    correct_answer: ".iso.",
  },
  {
    subject: "Gestión de bases de datos",
    title:
      "¿Cómo podemos representar y definir los datos en un sistema de información sin tener en cuenta las necesidades tecnológicas?",
    answer_1: "Con un diagrama entidad/relación",
    answer_2: "Con el diccionario de datos.",
    answer_3: "Con Pseudocódigo",
    answer_4: "Con un diagrama de cardinalidad.",
    correct_answer: "Con un diagrama entidad/relación",
  },
  {
    subject: "Gestión de bases de datos",
    title:
      "¿En que bloque se incluyen las sentencias y estructuras de la lógica del procedimiento?",
    answer_1: "En el bloque BEGIN",
    answer_2: "Después de END",
    answer_3: "En el bloque DECLARE",
    answer_4: "En el bloque EXCEPTION",
    correct_answer: "En el bloque BEGIN",
  },
  {
    subject: "Gestión de bases de datos",
    title: "¿Para qué sirven los índices?",
    answer_1:
      "Permiten agilizar el acceso a un campo mediante la organizando su información",
    answer_2: "Representa un índice de objetos de los metadatos.",
    answer_3: "Para saber el número de entidades que hay.",
    answer_4: "Define la clave primaria de una entidad.",
    correct_answer:
      "Permiten agilizar el acceso a un campo mediante la organizando su información",
  },
  {
    subject: "Gestión de bases de datos",
    title: "¿PL/SQL es compatible con todos los SGBD?",
    answer_1: "No, PL/SQL sirve para Oracle y PL/pgSQL para PostgreSQL",
    answer_2: "Sí, contiene estructuras que entienden todos los SGBD.",
    answer_3: "Sí, hay un estándar de aplicación.",
    answer_4: "Sí.",
    correct_answer: "No, PL/SQL sirve para Oracle y PL/pgSQL para PostgreSQL",
  },
  {
    subject: "Gestión de bases de datos",
    title:
      "¿Qué condición tiene que cumplir en la segunda forma normal (2FN)?:",
    answer_1: "Debe estar en la primera forma normal.",
    answer_2: "Debe estar en la tercera forma normal.",
    answer_3: "Puede tener valores atómicos.",
    answer_4: "Sus campos no dependen de la clave primaria.",
    correct_answer: "Debe estar en la primera forma normal.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "¿Qué es un sistema gestor de base de datos?",
    answer_1:
      "Un software con herramientas de administración y gestión de base de datos",
    answer_2: "Un software de diseño de base de datos.",
    answer_3: "Un tipo de base de datos",
    answer_4: "Un software para programar una base de datos",
    correct_answer:
      "Un software con herramientas de administración y gestión de base de datos",
  },
  {
    subject: "Gestión de bases de datos",
    title: "¿Qué instrucción necesitamos para ver la estructura de una tabla?",
    answer_1: "DESC",
    answer_2: "ESTRUCT",
    answer_3: "SHOW TABLES",
    answer_4: "SHOW DATABASES",
    correct_answer: "DESC",
  },
  {
    subject: "Gestión de bases de datos",
    title: "¿Qué instrucción nos permite modificar una tabla?",
    answer_1: "ALTER TABLE",
    answer_2: "UPDATE",
    answer_3: "INSERT",
    answer_4: "DROP TABLE",
    correct_answer: "ALTER TABLE",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Bucle preparado con un numero de repeticiones predeterminadas:",
    answer_1: "Bucle FOR.",
    answer_2: "Bucle con WHILE.",
    answer_3: "Bucle básico LOOP.",
    answer_4: "Bucle ELSE.",
    correct_answer: "Bucle FOR.",
  },
  {
    subject: "Gestión de bases de datos",
    title:
      "CREATE DATABASE nombre_bd; permite crear una base de datos empleando el lenguaje:",
    answer_1: "DDL.",
    answer_2: "DML.",
    answer_3: "DCL.",
    answer_4: "Todas las anteriores son incorrectas.",
    correct_answer: "DDL.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Cuando hablamos de integridad referencial...",
    answer_1: "Todas son correctas",
    answer_2:
      "Cualquier cambio en un registro que está relacionado se trasmite en cascada.",
    answer_3:
      "No podemos borrar un registro que está relacionado con otra mediante su clave foránea.",
    answer_4: "Establecer valores nulos en claves foráneas",
    correct_answer: "Todas son correctas",
  },
  {
    subject: "Gestión de bases de datos",
    title:
      "Cuando se almacena una dirección o puntero en vez del valor de la información, estamos hablando de:",
    answer_1: "Referencias",
    answer_2: "Datos extrapolados",
    answer_3: "Datos físicos",
    answer_4: "Herencia",
    correct_answer: "Referencias",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Cuando tenemos una transferencia de datos entre distintos SGBD",
    answer_1:
      "Es una tarea importante, cada SGDB tiene diferentes características y hay que adaptarlas según el cambio.",
    answer_2: "Un tipo de datos se usa igual independientemente del SGBD",
    answer_3:
      "No hay que preocuparse todos los SGDB tienen las mismas características",
    answer_4: "Solo se puede hacer entre el mismo tipo de base de datos",
    correct_answer:
      "Es una tarea importante, cada SGDB tiene diferentes características y hay que adaptarlas según el cambio.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "El lenguaje más empleado en bases de datos es:",
    answer_1: "SQL.",
    answer_2: "SDL.",
    answer_3: "SUL.",
    answer_4: "SFL.",
    correct_answer: "SQL.",
  },
  {
    subject: "Gestión de bases de datos",
    title:
      "Es el lenguaje que usaremos para administrar la seguridad de los datos mediante permisos y usuarios.",
    answer_1: "DCL.",
    answer_2: "DML.",
    answer_3: "DDL.",
    answer_4: "Todas las anteriores son incorrectas.",
    correct_answer: "DCL.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Es un tipo de copia de seguridad",
    answer_1: "Incrementales",
    answer_2: "Decrementales",
    answer_3: "Incompletas",
    answer_4: "Existenciales.",
    correct_answer: "Incrementales",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Es un tipo de modelo de base de datos",
    answer_1: "Todas son correctas",
    answer_2: "Modelo en red",
    answer_3: "Modelo relacional",
    answer_4: "Modelo orientado a objetos",
    correct_answer: "Todas son correctas",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Es un tipo de organización de los soportes de almacenamiento",
    answer_1: "Multiplexado",
    answer_2: "Aleatorio",
    answer_3: "Secuencial",
    answer_4: "Concatenado",
    correct_answer: "Secuencial",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Es un tipo de relación",
    answer_1: "Reflexivas",
    answer_2: "Expresivas",
    answer_3: "Comunicativas",
    answer_4: "Concatenarías",
    correct_answer: "Reflexivas",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Es una consecuencia de las bases de datos objeto-relacionales:",
    answer_1: "Que las tablas no sean elementos bidimensionales.",
    answer_2: "Todas son incorrectas",
    answer_3: "Que no tengamos campos atómicos.",
    answer_4: "A y B son correctas.",
    correct_answer: "A y B son correctas.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Es una función de agregación o resumen",
    answer_1: "COUNT()",
    answer_2: "MOD()",
    answer_3: "RESTA()",
    answer_4: "TOTAL()",
    correct_answer: "COUNT()",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Estructura de control que emplea las sentencias IF y CASE:",
    answer_1: "Selección.",
    answer_2: "Iteración.",
    answer_3: "Segmentación.",
    answer_4: "Todas las anteriores son incorrectas.",
    correct_answer: "Selección.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Existen dos tipos de clave, la primaria y:",
    answer_1: "La candidata.",
    answer_2: "La exclusiva.",
    answer_3: "La secundaria.",
    answer_4: "La jerarquizada.",
    correct_answer: "La candidata.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "La clave primaria:",
    answer_1: "Puede estar formada por un único campo o ser compuesta.",
    answer_2: "Ninguna de las anteriores.",
    answer_3: "Puede ser única.",
    answer_4: "Se deriva de la clave secundaria.",
    correct_answer: "Puede estar formada por un único campo o ser compuesta.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "La POO sirve para:",
    answer_1: "Todas son incorrectas.",
    answer_2: "Desarrollar solo software privativo",
    answer_3: "Que otros paradigmas se basen en esta.",
    answer_4: "Fallos de software.",
    correct_answer: "Que otros paradigmas se basen en esta.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "La sentencia UPDATE nos permite:",
    answer_1: "La modificación de registros.",
    answer_2: "La Eliminación de registros.",
    answer_3: "La consulta de registros sobre varias tablas.",
    answer_4: "Ninguna de las anteriores es correcta.",
    correct_answer: "La modificación de registros.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Lenguaje que se centra en la consulta de información:",
    answer_1: "DML.",
    answer_2: "Ninguna de las anteriores.",
    answer_3: "DDL.",
    answer_4: "DCL.",
    correct_answer: "DML.",
  },
  {
    subject: "Gestión de bases de datos",
    title:
      "Lo que en un modelo entidad/ relación es una entidad, en un modelo físico es llamado:",
    answer_1: "Tabla.",
    answer_2: "Entidad.",
    answer_3: "Registro.",
    answer_4: "Tipo.",
    correct_answer: "Tabla.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Los fallos lógicos:",
    answer_1: "A Y B son correctas.",
    answer_2: "Un virus es un fallo lógico.",
    answer_3: "Son los que se producen por fallos de software.",
    answer_4: "Son los que se producen por fallos de hardware.",
    correct_answer: "A Y B son correctas.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Los ficheros:",
    answer_1: "Puede contener tanto texto plano como binario.",
    answer_2: "Contienen texto plano.",
    answer_3: "Tienen su propio sistema de escritura.",
    answer_4: "Contienen código binario.",
    correct_answer: "Puede contener tanto texto plano como binario.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "M:N es un concepto de:",
    answer_1: "Las claves.",
    answer_2: "La cardinalidad.",
    answer_3: "La modalidad.",
    answer_4: "Multidimensional.",
    correct_answer: "La cardinalidad.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "MySQL es:",
    answer_1: "Un SGBD.",
    answer_2: "Un tipo de base de datos.",
    answer_3: "Un sublenguaje de SQL.",
    answer_4: "Ninguna de las anteriores.",
    correct_answer: "Un SGBD.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Para buscar un patrón de una cadena de caracteres usaremos...",
    answer_1: "LIKE",
    answer_2: "BETWEEN",
    answer_3:
      "Se incluirá todos los casos posibles y se unirán con el operador lógico AND",
    answer_4: "No se puede buscar patrones de cadenas de caracteres",
    correct_answer: "LIKE",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Para solucionar un fallo físico:",
    answer_1: "La gestión de los backups es una buena opción.",
    answer_2: "Todas las anteriores son correctas.",
    answer_3: "Podemos tirar todo y comprar nuevos equipos.",
    answer_4: "No es necesario recuperar un fallo físico.",
    correct_answer: "La gestión de los backups es una buena opción.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "PL/SQL no puede soportar:",
    answer_1: "DDL.",
    answer_2: "DML.",
    answer_3: "Los dos anteriores.",
    answer_4: "Todas las anteriores son incorrectas.",
    correct_answer: "DDL.",
  },
  {
    subject: "Gestión de bases de datos",
    title:
      "Que debemos tener en cuenta en la gestión de fallos lógicos en una base de datos",
    answer_1: "Todas son correctas",
    answer_2: "Autenticación en el SGBD",
    answer_3:
      "Controlar los accesos a los servicios y recursos de las bases de datos, como al servidor propio.",
    answer_4: "Gestión de perfiles y usuarios.",
    correct_answer: "Todas son correctas",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Se pueden usar para los subtipos y supertipos las cláusulas:",
    answer_1: "Todas las anteriores son correctas.",
    answer_2: "FINAL.",
    answer_3: "NOT FINAL.",
    answer_4: "UNDER.",
    correct_answer: "Todas las anteriores son correctas.",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Si queremos seleccionar unos datos y que no estén repetidos ...",
    answer_1: "Hay que incluir DISTINCT",
    answer_2: "Se utilizará el operador <>",
    answer_3:
      "Tenemos que preocuparnos se insertar los datos que no estén repetidos",
    answer_4: "En las bases de datos relacionales esto no puede suceder",
    correct_answer: "Hay que incluir DISTINCT",
  },
  {
    subject: "Gestión de bases de datos",
    title: "Un tipo que puede almacenar una colección es considerado como:",
    answer_1: "Array",
    answer_2: "Tablas",
    answer_3: "Columnas",
    answer_4: "Filas",
    correct_answer: "Array",
  },
  {
    subject: "Gestión de bases de datos",
    title: "UNIQUE es:",
    answer_1:
      "Una restricción en SQL se utiliza para garantizar que no se inserten valores duplicados en una columna.",
    answer_2:
      "Una restricción en SQL se utiliza para garantizar los valores tipo NULL.",
    answer_3:
      "Una restricción en SQL se utiliza para garantizar que no se inserten valores con un formato diferente al destinado.",
    answer_4: "Ninguna de las anteriores.",
    correct_answer:
      "Una restricción en SQL se utiliza para garantizar que no se inserten valores duplicados en una columna.",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "¿A qué herramienta podemos acceder desde el Centro de administración del servidor para administrar los equipos de un dominio en Windows Server?",
    answer_1: "Administrador de dominio",
    answer_2: "Administración de equipos",
    answer_3: "Configuración de equipos",
    answer_4: "Panel de control",
    correct_answer: "Administración de equipos",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "¿Cuál de las siguientes acciones es la adecuada si queremos ver las actualizaciones disponibles del fabricante del hardware en Windows?",
    answer_1: "Buscar en la web oficial del fabricante del software",
    answer_2: "Utilizar el Administrador de dispositivos en Windows",
    answer_3: "Reiniciar el equipo y verificar las actualizaciones automáticas",
    answer_4: "Descargar e instalar el software de actualización de Windows",
    correct_answer: "Utilizar el Administrador de dispositivos en Windows",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "¿Cuál de las siguientes afirmaciones es correcta sobre las terminales de Windows y Linux?",
    answer_1:
      "Windows distingue entre mayúsculas y minúsculas en los comandos, mientras que Linux no lo hace",
    answer_2:
      "Linux distingue entre mayúsculas y minúsculas en los comandos, mientras que Windows no lo hace",
    answer_3:
      "Tanto Windows como Linux distinguen entre mayúsculas y minúsculas en los comandos",
    answer_4: "Windows y Linux no permiten escribir comandos en sus terminales",
    correct_answer:
      "Linux distingue entre mayúsculas y minúsculas en los comandos, mientras que Windows no lo hace",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "¿Cuál de las siguientes es una de las 4 libertades del software libre?",
    answer_1: "Utilizar",
    answer_2: "Las 3 forman parte de estas 4 libertades",
    answer_3: "Mejorar",
    answer_4: "Estudiar",
    correct_answer: "Las 3 forman parte de estas 4 libertades",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "¿Cuál de las siguientes es una medida para asegurar contraseñas en los sistemas operativos?",
    answer_1: "Utilizar algoritmos para elección de contraseñas",
    answer_2: "Todas las anteriores",
    answer_3: "Obligar a los usuarios a cambiar las contraseñas",
    answer_4: "Utilizar mayúsculas en las contraseñas",
    correct_answer: "Todas las anteriores",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "¿Cuál de las siguientes opciones es una descripción adecuada del recurso compartido “IPC$” en un sistema Windows Server?",
    answer_1:
      "Contiene las carpetas de los usuarios del servidor donde se encuentra el Directorio Activo",
    answer_2:
      "Comparte las canalizaciones esenciales para la comunicación entre programas",
    answer_3:
      "Almacena el servicio de inicio de sesión para los controladores de dominio",
    answer_4: "Es una ubicación predeterminada para compartir archivos de red",
    correct_answer:
      "Comparte las canalizaciones esenciales para la comunicación entre programas",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "¿Cuál es el directorio de Windows que contiene principalmente los archivos del sistema y que incluye subdirectorios como System32, Boot, Help, PolicyDefinitions, Fonts y Temp?",
    answer_1: "Archivos de programa x86",
    answer_2: "Windows",
    answer_3: "Archivos de programa",
    answer_4: "Temp",
    correct_answer: "Windows",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "¿En qué carpetas del AD se guardan los grupos creados durante una instalación?",
    answer_1: "A y B son correctas",
    answer_2: "Builtin",
    answer_3: "Users",
    answer_4: "Todas son incorrectas",
    correct_answer: "A y B son correctas",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "¿En qué sistema se introduce el concepto de dominio?",
    answer_1: "En Ubuntu",
    answer_2: "En Windows",
    answer_3: "En Linux",
    answer_4: "En Mac",
    correct_answer: "En Windows",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "¿Por qué no se recomienda eliminar directamente una Unidad Organizativa en un entorno empresarial?",
    answer_1: "Puede provocar problemas de rendimiento en la red",
    answer_2:
      "Puede resultar en la pérdida de información y configuraciones importantes",
    answer_3: "Puede causar errores en la autenticación de usuarios",
    answer_4: "Puede afectar a la estabilidad del sistema operativo",
    correct_answer:
      "Puede resultar en la pérdida de información y configuraciones importantes",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "¿Por qué no se recomienda usar la cuenta de usuario invitado de Windows Server?",
    answer_1: "Porque está deshabilitada de manera automática",
    answer_2: "Porque su uso puede ser un fallo de seguridad",
    answer_3: "Porque es una cuenta temporal para usuarios momentáneos",
    answer_4:
      "Porque es difícil identificar las acciones realizadas por este usuario",
    correct_answer: "Porque su uso puede ser un fallo de seguridad",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "¿Qué es la encriptación de datos?",
    answer_1: "Un sistema de directorios utilizado en sistemas de ficheros",
    answer_2:
      "Un proceso de convertir información legible en un formato ilegible y protegido mediante el uso de algoritmos y claves especiales",
    answer_3:
      "Un tipo de copia de seguridad que se centra en los archivos que han experimentado cambios desde la creación de la copia base",
    answer_4:
      "Una forma en la que los usuarios interactúan con un sistema informático",
    correct_answer:
      "Un proceso de convertir información legible en un formato ilegible y protegido mediante el uso de algoritmos y claves especiales",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "¿Qué es NTFS en el contexto de un sistema de archivos en Windows?",
    answer_1:
      "Non-Transfearable File Storage, un sistema de archivos que no permite la transferencia de archivos entre dispositivos",
    answer_2:
      "New Technology File System, un Sistema de archivos utilizado en sistemas de almacenamiento de datos",
    answer_3:
      "Network Transfer File System, un Sistema de archivos utilizado para compartir archivos en redes locales",
    answer_4:
      "New Transmission File Structure, un Sistema de archivos diseñado para la transferencia de datos de manera eficiente",
    correct_answer:
      "New Technology File System, un Sistema de archivos utilizado en sistemas de almacenamiento de datos",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "¿Qué es una auditoría en Windows?",
    answer_1: "Lo mismo que una directiva de grupo",
    answer_2:
      "Un método de monitorización de sucesos relacionados con la seguridad del sistema",
    answer_3: "Una GPO",
    answer_4: "Ninguna es correcta",
    correct_answer:
      "Un método de monitorización de sucesos relacionados con la seguridad del sistema",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "¿Qué es una Unidad Organizativa en el Directorio Activo?",
    answer_1:
      "Un conjunto de reglas y configuraciones para garantizar la seguridad de la red",
    answer_2:
      "Un contenedor lógico usado para organizar y gestionar objetos relacionados en un dominio",
    answer_3:
      "Una dirección de red que sirve de conexión a un equipo para salir a otra red externa",
    answer_4:
      "Un comando usado en sistemas Windows para mostrar y gestionar la configuración de red",
    correct_answer:
      "Un contenedor lógico usado para organizar y gestionar objetos relacionados en un dominio",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "¿Qué se recomienda hacer antes de unir un equipo a un dominio?",
    answer_1: "Cambiar su IP por una pública",
    answer_2: "Cambiar su nombre de equipo",
    answer_3: "Cambiar su configuración de escritorio",
    answer_4: "Todas son incorrectas",
    correct_answer: "Cambiar su nombre de equipo",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "¿Qué sucede cuando se heredan permisos en una carpeta NTFS en Windows?",
    answer_1: "Los permisos de la carpeta se eliminan por completo",
    answer_2:
      "Los permisos de la carpeta se combinan con los permisos de la carpeta superior",
    answer_3:
      "Los permisos de la carpeta se reemplazan por los permisos de la carpeta superior",
    answer_4: "Los permisos de la carpeta se duplican",
    correct_answer:
      "Los permisos de la carpeta se reemplazan por los permisos de la carpeta superior",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "¿Qué usuario crea automáticamente Windows Server cuando se instala?",
    answer_1: "El usuario de dominio",
    answer_2: "El usuario administrador",
    answer_3: "El usuario moderador",
    answer_4: "El usuario sin privilegios que queramos",
    correct_answer: "El usuario administrador",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "¿Se pueden editar los permisos de una carpeta compartida en Windows?",
    answer_1: "Depende del usuario al que se le vaya a dar permisos",
    answer_2: "Sí",
    answer_3: "No",
    answer_4: "Depende de la versión de la carpeta",
    correct_answer: "Sí",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "El comando ls -l /home/root | wc -l, ¿qué hace?",
    answer_1:
      "Muestra por pantalla las líneas que da la salida del comando ls -l del directorio /home/root",
    answer_2:
      "Indica que número de líneas debe de tener todo el directorio /home",
    answer_3:
      "Muestra por pantalla el resultado de ambos comandos, salida del directorio y líneas totales",
    answer_4:
      "Muestra por pantalla una línea más a la salida del primer comando que ponga las líneas de cada fichero",
    correct_answer:
      "Muestra por pantalla las líneas que da la salida del comando ls -l del directorio /home/root",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "El comando para comprobar el software instalado en Windows es:",
    answer_1: "Apt",
    answer_2: "Wmic",
    answer_3: "Cdl",
    answer_4: "Micw",
    correct_answer: "Wmic",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "El comando tracerpt genera dos archivos principalmente:",
    answer_1: "Uno en texto plano y otro en HTML",
    answer_2: "Uno XML y otro en texto plano",
    answer_3: "Uno XML y otro en HTML",
    answer_4: "Los dos en XML",
    correct_answer: "Uno XML y otro en texto plano",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "El visor de eventos es:",
    answer_1: "Una herramienta nativa del sistema",
    answer_2: "Todas son correctas",
    answer_3: "Una herramienta para visualizar los registros del sistema",
    answer_4:
      "Una herramienta para visualizar los registros de seguridad del sistema",
    correct_answer: "Todas son correctas",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "En Linux se puede configurar una red:",
    answer_1: "Por comandos",
    answer_2: "A y B son correctas",
    answer_3: "Gráficamente",
    answer_4: "Todas son incorrectas",
    correct_answer: "A y B son correctas",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "En Linux, el directorio al que se mandan los archivos eliminados es:",
    answer_1: "/temp/drop",
    answer_2: "/dev/null",
    answer_3: "/temp/null",
    answer_4: "/dev/drop",
    correct_answer: "/dev/null",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "En los registros de Windows del Visor de eventos, se almacenan:",
    answer_1:
      "Los registros referentes al sistema en sí y las acciones del mismo",
    answer_2: "Los registros de una aplicación en concreto",
    answer_3: "Los eventos de equipos remotos",
    answer_4: "Solo advertencias",
    correct_answer:
      "Los registros referentes al sistema en sí y las acciones del mismo",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "En Windows, ¿existen directivas de grupo por defecto?",
    answer_1: "No",
    answer_2: "Sí",
    answer_3: "Solo en Windows Server Essentials",
    answer_4: "Solo en Windows Server Datacenter",
    correct_answer: "Sí",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "Es una recomendación a la hora de elaborar un manual de usuario:",
    answer_1: "Poner el nombre del usuario que lo va a leer",
    answer_2: "Incluir la fecha de creación del manual",
    answer_3: "Indicar que nivel de dificultad tiene el manual",
    answer_4: "Todas son incorrectas",
    correct_answer: "Incluir la fecha de creación del manual",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "Indica cuál de los siguientes es un parámetro del monitor de rendimiento de Windows:",
    answer_1: "Mínimo",
    answer_2: "Todos son parámetros del monitor de rendimiento",
    answer_3: "Máximo",
    answer_4: "Promedio",
    correct_answer: "Todos son parámetros del monitor de rendimiento",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "Indica las diferencias entre eliminar unos objetos del AD u otros:",
    answer_1:
      "Los usuarios se eliminan desde un sitio y los demás objetos desde otro",
    answer_2: "No hay diferencias",
    answer_3: "Los grupos se eliminan de un modo y los demás objetos de otro",
    answer_4: "Los equipos no se pueden eliminar y los demás objetos sí",
    correct_answer: "No hay diferencias",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "La asistencia a los usuarios puede ser:",
    answer_1: "Con ayuda de un técnico especializado",
    answer_2: "A y B son correctas",
    answer_3: "Sin ayuda de un técnico especializado",
    answer_4: "Siempre con ayuda de uno o varios técnicos",
    correct_answer: "A y B son correctas",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "La herramienta de Windows donde se ven los registros del sistema es:",
    answer_1: "Regedit",
    answer_2: "/var/log",
    answer_3: "/log/var",
    answer_4: "Synaptics",
    correct_answer: "Regedit",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "Las incidencias de las que no conocemos ni su origen ni su manera de actuar son:",
    answer_1: "Problemas conocidos",
    answer_2: "Sin conocimiento",
    answer_3: "Errores conocidos",
    answer_4: "Problemas en conocimiento",
    correct_answer: "Sin conocimiento",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "¿Qué se requiere poder completar una conexión mediante Escritorio Remoto en Windows Server?",
    answer_1: "Una IP pública del servidor y cualquier contraseña",
    answer_2: "Un usuario y contraseña válidos del servidor para autenticarse",
    answer_3: "Solo el nombre del servidor sin necesidad de autenticación",
    answer_4:
      "Conexión física directa al servidor sin necesidad de autenticación remota",
    correct_answer:
      "Un usuario y contraseña válidos del servidor para autenticarse",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "Que los usuarios tengan que cambiar las contraseñas cada tres meses es:",
    answer_1: "Una directiva de autenticación única de Linux",
    answer_2: "Un protocolo de seguridad en todos los sistemas",
    answer_3: "Un método de cifrado",
    answer_4: "Todas son correctas",
    correct_answer: "Un protocolo de seguridad en todos los sistemas",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "Si entregamos un equipo informático a un usuario de nuestra empresa, ¿qué es importante que conozcan?",
    answer_1: "El funcionamiento de las aplicaciones",
    answer_2: "Todas son correctas",
    answer_3: "Donde se encuentran los manuales de usuario",
    answer_4: "Posibles errores",
    correct_answer: "Todas son correctas",
  },
  {
    subject: "Implantación de sistemas operativos",
    title:
      "Si queremos mover el archivo examen con confirmación del directorio home al directorio etc, deberíamos usar, ¿qué comando?",
    answer_1: "cp -i ~/examen/etc",
    answer_2: "mv -i examen /etc",
    answer_3: "mv ~/examen /etc",
    answer_4: "Ninguna es correcta",
    correct_answer: "Ninguna es correcta",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "Son sucesos susceptibles de auditar:",
    answer_1: "El acceso a objetos del sistema",
    answer_2: "Todas son correctas",
    answer_3: "El inicio y fin de una sesión de usuario",
    answer_4: "La administración de cuentas de usuario y grupos",
    correct_answer: "Todas son correctas",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "Un cliente de correo, ¿dónde lo podemos englobar?",
    answer_1: "Aplicaciones específicas de programación",
    answer_2: "Aplicaciones ofimáticas",
    answer_3: "Aplicaciones específicas de contabilidad",
    answer_4: "Todas son incorrectas",
    correct_answer: "Aplicaciones ofimáticas",
  },
  {
    subject: "Implantación de sistemas operativos",
    title: "Un evento del sistema es:",
    answer_1: "Una aplicación nativa",
    answer_2: "Un procedimiento interno del sistema",
    answer_3: "Un suceso ocurrido fuera del sistema",
    answer_4: "Un suceso o notificación con cierta importancia en el sistema",
    correct_answer:
      "Un suceso o notificación con cierta importancia en el sistema",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "¿Qué es XQuery?",
    answer_1: "Lenguaje de consultas especializado en datos XML.",
    answer_2: "Lenguaje de procesamiento de documentos XML.",
    answer_3: "Lenguaje de verificación empleado por DTD",
    answer_4: "Todas las anteriores son incorrecta.",
    correct_answer: "Lenguaje de consultas especializado en datos XML.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "Como se denomina el elemento que modifica una etiqueta",
    answer_1: "Etiqueta.",
    answer_2: "Gramática.",
    answer_3: "Elemento.",
    answer_4: "Atributo.",
    correct_answer: "Atributo.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "Con que programa podemos crear un documento HTML",
    answer_1: "Kompozer",
    answer_2: "Bloc de Notas.",
    answer_3: "HTML Online Editor.",
    answer_4: "Todas las anteriores son correctas.",
    correct_answer: "Todas las anteriores son correctas.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "CSS son las siglas de:",
    answer_1: "Code Sheets Style.",
    answer_2: "Code Style Sheets.",
    answer_3: "Cascading Style Sheets.",
    answer_4: "Cascading Sheets Style.",
    correct_answer: "Cascading Style Sheets.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title:
      "¿Cuál de las siguientes extensiones no corresponde con un archivo de lenguaje de marcas?",
    answer_1: ".css",
    answer_2: ".sgml",
    answer_3: ".html.",
    answer_4: ".xml.",
    correct_answer: ".css",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "¿Cuál de las siguientes opciones no es una etiqueta específica?",
    answer_1: "<xsl:value-of>",
    answer_2: "<xsl:for-each>",
    answer_3: "<xsl:boolean›",
    answer_4: "<xsl:choose>",
    correct_answer: "<xsl:boolean›",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title:
      "Cuál de los siguientes no es un formato para el intercambio y almacenamiento de los datos:",
    answer_1: "Ficheros CSV.",
    answer_2: "Ficheros JSON.",
    answer_3: "Ficheros XML.",
    answer_4: "Fichero TEMP.",
    correct_answer: "Fichero TEMP.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title:
      "Cuál es el símbolo faltante, marcado con (…), en esta etiqueta xsl, <xsl(...)value-of:",
    answer_1: "igual.",
    answer_2: "?, interrogación.",
    answer_3: "_, barra baja.",
    answer_4: ":, Dos puntos.",
    correct_answer: ":, Dos puntos.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "Documento que permite validar un documento XML:",
    answer_1: "DTD.",
    answer_2: "OS/2.",
    answer_3: "SASS.",
    answer_4: "Ninguna de las anteriores es correcta.",
    correct_answer: "DTD.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "DTD es:",
    answer_1: "Un sistema numérico.",
    answer_2: "Un tipo de atributo.",
    answer_3: "Un documento de verificación.",
    answer_4: "Un tipo de etiqueta.",
    correct_answer: "Un documento de verificación.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "El atributo CDATA de DTD implica que el valor:",
    answer_1: "Es un contenido único e inequívoco.",
    answer_2: "Refiere a otro elemento",
    answer_3: "Es alfanumérico.",
    answer_4: "Ninguna de las anteriores es correcta.",
    correct_answer: "Es alfanumérico.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title:
      "El módulo encargado de permitir la venta online mediante el pago electrónico es:",
    answer_1: "Módulo de TPV.",
    answer_2: "Módulo de Marketing.",
    answer_3: "Módulo de proyectos.",
    answer_4: "Módulo de gestión de almacenes.",
    correct_answer: "Módulo de TPV.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "En un DTD #IMPLIED implica que el atributo:",
    answer_1: "Es obligatorio.",
    answer_2: "Ninguna de las anteriores es correcta.",
    answer_3: "Es fijo.",
    answer_4: "Es opcional.",
    correct_answer: "Es opcional.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "Elementos básicos de un feed que se deben introducir en channel:",
    answer_1: "Title, link y URL.",
    answer_2: "Title, link e imagen.",
    answer_3: "Title, URL y description.",
    answer_4: "Title, link y description.",
    correct_answer: "Title, link y description.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title:
      "En el lenguaje XPath usa expresiones de ruta como “/” el cual permite la selección de:",
    answer_1: "El nodo con un nombre específico.",
    answer_2: "Todas las anteriores son incorrectas.",
    answer_3: "Selecciona el nodo actual.",
    answer_4: "El nodo raíz.",
    correct_answer: "El nodo raíz.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title:
      "En esta regla de CSS:  h2 { color: #B6E1F9; } como llamamos al elemento “color”",
    answer_1: "Selector",
    answer_2: "Declaración",
    answer_3: "Propiedad.",
    answer_4: "Valor",
    correct_answer: "Propiedad.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "En HTML la etiqueta <link> determina:",
    answer_1: "La versión.",
    answer_2: "Estándar empleado.",
    answer_3: "Recursos externos, hojas de estilo, empleados.",
    answer_4: "Estilos empleados.",
    correct_answer: "Recursos externos, hojas de estilo, empleados.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "En las hojas de estilo XSL el símbolo / en solitario indica:",
    answer_1: "Un comentario.",
    answer_2: "Todos los anteriores son correctos.",
    answer_3: "Un valor.",
    answer_4: "Un atributo.",
    correct_answer: "Un valor.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "En XML los valores siempre deben:",
    answer_1: "Ser numéricos.",
    answer_2: "Acotarse con los símbolos “<” y “>”.",
    answer_3: "Ir entre símbolos de igual.",
    answer_4: "Entrecomillarse.",
    correct_answer: "Entrecomillarse.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "En XPath “|” permite:",
    answer_1: "Computar dos nodos simultáneos.",
    answer_2: "Ninguna de las anteriores es correcta ese símbolo no se emplea.",
    answer_3:
      "Marcar una disyunción entre uno o más nodos entre los que elegir.",
    answer_4: "Dividir los valores de dos nodos.",
    correct_answer: "Computar dos nodos simultáneos.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "Entre los elementos secundarios de channel, el elemento ttl:",
    answer_1: "Marca la fecha de publicación.",
    answer_2: "El tipo de licencia.",
    answer_3: "Marca el tiempo de actualización en el caché.",
    answer_4: "Todas las anteriores son incorrectas.",
    correct_answer: "Marca el tiempo de actualización en el caché.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "HTML son las siglas de:",
    answer_1: "Hypertext Markup Language",
    answer_2: "Hypertext Medium Language.",
    answer_3: "Hyperlink Meta List.",
    answer_4: "Hiperlink Mask Line",
    correct_answer: "Hypertext Markup Language",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "La estructura de XML consta de:",
    answer_1: "Prólogo y directorio.",
    answer_2: "Índice y cuerpo.",
    answer_3: "Prólogo y cuerpo.",
    answer_4: "Todas las anteriores son incorrectas",
    correct_answer: "Prólogo y cuerpo.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "La información XML se puede almacenar en forma de:",
    answer_1: "Ficheros.",
    answer_2: "XML enabled.",
    answer_3: "Bases de datos nativas en XML.",
    answer_4: "Todas son correctas",
    correct_answer: "Todas son correctas",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "La seguridad de los ERP:",
    answer_1:
      "No es muy alta, por lo que se deben implementar medidas por parte de la empresa.",
    answer_2:
      "No es muy alta, pero un mínimo cuidado por parte de la empresa es suficiente.",
    answer_3:
      "Es muy alta, por lo que no requiere de otras medidas por parte de la empresa.",
    answer_4:
      "Es muy alta, pero, además, se recomienda que la empresa tome sus propias medidas de seguridad adicional",
    correct_answer:
      "Es muy alta, pero, además, se recomienda que la empresa tome sus propias medidas de seguridad adicional",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "La sintaxis FLOWR es un acrónimo de For, Let, Where, Order by y….",
    answer_1: "Rearrange.",
    answer_2: "React.",
    answer_3: "Return.",
    answer_4: "Remove.",
    correct_answer: "Return.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "Las bases de datos XML enabled son:",
    answer_1: "Bases de datos no nativas.",
    answer_2: "Bases de datos relacionales.",
    answer_3: "Bases de datos que trabajan con XML.",
    answer_4: "Todas las anteriores son correctas.",
    correct_answer: "Todas las anteriores son correctas.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "Las marcas de cierre:",
    answer_1: "Son iguales que las de apertura.",
    answer_2: "Se marcan con /.",
    answer_3: "Se marcan con =.",
    answer_4: "Se marcan con ?.",
    correct_answer: "Se marcan con /.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "Los agregadores pueden ser:",
    answer_1: "Online.",
    answer_2: "De escritorio.",
    answer_3: "De clientes de correo web y navegadores web.",
    answer_4: "Todas las anteriores son correctas.",
    correct_answer: "Todas las anteriores son correctas.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "Los lenguajes de marcas se pueden utilizar en:",
    answer_1: "Páginas web.",
    answer_2: "Mensajería instantánea.",
    answer_3: "Sindicación de contenidos.",
    answer_4: "Todas son correctas.",
    correct_answer: "Todas son correctas.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "Los lenguajes XML y HTMLS se incluyen en el tipo de lenguaje:",
    answer_1: "Tipo 1 o de procedimiento.",
    answer_2: "En todos los anteriores.",
    answer_3: "Tipo 3 o descriptivos o semánticos.",
    answer_4: "Tipo 2 o de presentación.",
    correct_answer: "Tipo 3 o descriptivos o semánticos.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title:
      "Los sistemas de gestión empresarial requieren de múltiples herramientas, por lo que:",
    answer_1:
      "Se recomienda emplear múltiples herramientas específicas individuales.",
    answer_2:
      "Se recomiendo realizarlo todo en una única herramienta, aunque no sea lo ideal.",
    answer_3:
      "Se recomienda emplear un único sistema con diversas herramientas incorporadas, para evitar problemas de incompatibilidad.",
    answer_4:
      "Lo sistemas de gestión empresarial deben hacer uso de una única herramienta.",
    correct_answer:
      "Se recomienda emplear un único sistema con diversas herramientas incorporadas, para evitar problemas de incompatibilidad.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "Los tres pilares de los CRM son:",
    answer_1: "Marketing, venta y servicio postventa.",
    answer_2: "Marketing, compra y servicio postventa.",
    answer_3: "Marketing, venta y análisis.",
    answer_4: "Marketing, compra y análisis.",
    correct_answer: "Marketing, venta y servicio postventa.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "¿Qué debe incluir el prólogo del documento XML?",
    answer_1: "Presentación",
    answer_2: "Ninguna es correcta",
    answer_3: "Estructura del documento",
    answer_4: "Versión",
    correct_answer: "Versión",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "¿Qué tipo de estructura jerárquica tiene un documento XML?",
    answer_1: "Estructura ascendente arbórea.",
    answer_2: "Estructura descendente canórea.",
    answer_3: "Estructura descendente arbórea.",
    answer_4: "Ninguna de las anteriores es correcta.",
    correct_answer: "Estructura descendente arbórea.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "Qué tipo de sindicación se utiliza en este documento XML.",
    answer_1: "FeedTe.",
    answer_2: "Todos los anteriores son incorrectos.",
    answer_3: "ATOM.",
    answer_4: "RSS.",
    correct_answer: "ATOM.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "RSS hace referencia a:",
    answer_1: "Really Simple Syndication.",
    answer_2: "Real Sindication Simple .",
    answer_3: "Real Sindicate Simplified.",
    answer_4: "Todas las anteriores son incorrectas.",
    correct_answer: "Really Simple Syndication.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title:
      "Un texto que se encuentra en un símbolo menor que (<) y otro símbolo mayor que (>) se denomina:",
    answer_1: "Elemento.",
    answer_2: "Gramática.",
    answer_3: "Etiqueta.",
    answer_4: "Atributo.",
    correct_answer: "Etiqueta.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "XSL-FOR son las siglas de:",
    answer_1: "extensible stylesheet language formatting.",
    answer_2: "extensible stylesheet language formatting objects reload.",
    answer_3: "XML stylesheets language for transformation.",
    answer_4: "XSL-FOR no existe.",
    correct_answer: "XSL-FOR no existe.",
  },
  {
    subject: "Lenguajes de marcas y sistemas de gestión de información",
    title: "XSLT requiere la entrada de:",
    answer_1: "Una hoja de estilo.",
    answer_2: "Dos hojas de estilo.",
    answer_3: "Una hoja de estilo y un documento XML.",
    answer_4: "Dos documentos XML.",
    correct_answer: "Una hoja de estilo y un documento XML.",
  },
];
